miso-lims/runscanner

- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
This should indicate whether flowcell models are S1, S2, S4 (untested for SP)
> Update NovaSeq flowcell models

- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
Gracefully handle whitespace introduced by copy-paste from Excel
GLT-2665
> Handle latin1 characters in samplesheet

- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/IlluminaNotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/LS454NotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/NotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/PacBioNotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/ProgressiveRequestDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/ProgressiveResponseDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/SolidNotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/type/HealthType.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/type/IlluminaChemistry.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/type/Platform.java
- dto/src/test/java/ca/on/oicr/gsi/runscanner/rs/dto/test/IlluminaNotificationDtoTest.java
- dto/src/test/java/ca/on/oicr/gsi/runscanner/rs/dto/test/PacBioNotificationDtoTest.java
- pom.xml
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/Configuration.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/LatencyHistogram.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/Main.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/ParseNotificationJson.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/RestController.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/ScannerAppListener.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/Scheduler.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/StreamCountSpy.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/UserInterfaceController.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/WhineyFunction.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultPacBio.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/RunProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/Testing.java
- scanner/src/test/java/AbstractProcessorTest.java
- scanner/src/test/java/IlluminaProcessorTest.java
- scanner/src/test/java/PacBioProcessorTest.java
You probably only want to look at the `pom.xml`.
> Add Maven-based Google code formatting presubmit hook plugin

- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/IlluminaNotificationDto.java
- dto/src/test/java/ca/on/oicr/gsi/runscanner/rs/dto/test/IlluminaNotificationDtoTest.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
> Expose NovaSeq WorkflowType

- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/type/IlluminaChemistry.java
- scanner/src/test/resources/illumina/130417_M00146_0021_000000000-A2WDF/reference.json
This MISO change should be merged and released ahead of this Runscanner change being released: https://github.com/TGAC/miso-lims/pull/1827
> GLT-2639: fix detection of Illumina MiSeq chemistry

- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/BaseNanoporeProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/MinionProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/PromethionProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/RunProcessor.java
Parses from FAST5:
- Run Alias
- Container Serial Number
- Container Model
- Start time
- Software version
device_id doesn't seem to describe sequencerPosition for MinION, made that unique to PromethION, rest is shared.
> Beta MinION Processor

- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/NotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/OxfordNanoporeNotificationDto.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/BaseOxfordNanoporeProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/MinionProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/PromethionProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/Testing.java
> Update Oxford Nanopore DTOs

- README.md
Run Scanner User Manual is in progress, in the meantime, specify unique
settings required by nanopore sequencers in README
> Add ONT setup details to README

- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/UserInterfaceController.java
The main page does its job and better
> Remove the Instruments page

- runscanner-illumina/main.cpp
Based on Savo's input from https://github.com/miso-lims/miso-lims/issues/1483#issuecomment-397311508
> miso-lims#1483: fixed %>Q30 column labels; added density units

- docs/_includes/header.html
- docs/index.md
The pages themselves seem to work okay, just the table of contents isn't generating links correctly.
> Fix links in Table of Contents

- docs/pages/prometheus.md
- grafana-dashboard.json
Please have a look to see if I missed any reasons that `DroppedRuns` has fired.
> Write Prometheus manual section

- docs/pages/api.md
- docs/pages/illuminasetup.md
- docs/pages/main.md
- docs/pages/processing.md
- docs/pages/prometheus.md
- docs/pages/scanned.md
- docs/pages/scheduled.md
- docs/pages/unreadable.md
Since the API Docs page is documentation itself, not a ton to say here.
> User Manual page for API Docs

- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/IlluminaNotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/NotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/OxfordNanoporeNotificationDto.java
- dto/src/main/java/ca/on/oicr/gsi/runscanner/dto/PacBioNotificationDto.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/Configuration.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/FindRuns.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/ParseNotificationJson.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/ProcessRun.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/UserInterfaceController.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/BaseOxfordNanoporeProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultPacBio.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/PromethionProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/RunProcessor.java
- scanner/src/test/java/AbstractProcessorTest.java
- scanner/src/test/resources/oxfordnanopore/minion/20171007_1310_NA12878_NHT_DirectRNA_Run1/reference.json
- scanner/src/test/resources/oxfordnanopore/minion/20180224_1412_Minden_191224_dRNA_run1/reference.json
- scanner/src/test/resources/oxfordnanopore/promethion/20190221_2053_2-E3-H3_PAD10721_98c289ed/reference.json
- scanner/src/test/resources/oxfordnanopore/promethion/20190228_1936_1-A5-D5_PAD12953_01f009a3/reference.json
- scanner/src/test/resources/oxfordnanopore/promethion/20190228_1936_2-A5-D5_PAD13330_c59f16fe/reference.json
Make SonarCloud cry just a little less
> Sonar fixes

- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/RestResponseController.java
- null check is now in the right order
- switch from byte array to String already packaged in JsonNode to prevent corruption
> Fix /metrics endpoint

- docs/installation.md
Nested list doesn't format correctly, so make it all one level
> Fix nested list

- .travis.yml
As suggested here: https://travis-ci.community/t/packages-cannot-be-authenticated-google-chrome-stable-dpkg/6852
> use Travis Chrome addon

- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/BaseOxfordNanoporeProcessor.java
- scanner/src/test/resources/oxfordnanopore/promethion/20190228_1936_2-A5-D5_PAD13330_c59f16fe/final_summary.txt
- scanner/src/test/resources/oxfordnanopore/promethion/20190228_1936_2-A5-D5_PAD13330_c59f16fe/reference.json
So, I don't know what the file looks like while the sequencer is running. I'm making some guesses and I'll try to observe the instrument running and get a better idea.
> Try to use final_summary.txt for ONT runs

- docs/illuminasetup.md
> Include information about setting up runscanner-illumina PATH

- docs/README.md
- docs/appendices.md
and also clarify the README bc it threw me off
> No more sequel

- docs/appendices.md
JIRA Ticket: n/a
- [n/a] Updates release notes
- [n/a] Updates developer documentation
> Fix broken link in appendix

- RELEASE_NOTES.md
- docs/prometheus.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/Scheduler.java
JIRA Ticket: https://jira.oicr.on.ca/browse/GLT-3772
> [GLT-3772] add metric for last scan start time

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V1.13.4 snapshot pr

- .github/workflows/run_scanner_ci.yml
- README.md
- docs/illuminasetup.md
- docs/installation.md
- pom.xml
> [GLT-3827] Upgrade to Java 17

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V1.14.1 snapshot pr

- RELEASE_NOTES.md
- docs/appendices.md
- runscanner-illumina/main.cpp
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
> [GLT-3839] Update interop for NextSeq 2000 support

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V1.15.1 snapshot pr

- RELEASE_NOTES.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
JIRA Ticket: https://jira.oicr.on.ca/browse/GLT-3885
Cleaned up the xpath compiling and reading a bit too
> [GLT-3885] updated for NovaSeq X

- docs/appendices.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V1.16.1 snapshot pr

- .readthedocs.yml
JIRA Ticket: https://jira.oicr.on.ca/browse/GLT-4082
> [GLT-4082] add newly required build parameters to readthedocs config

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V1.16.2 snapshot pr

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V1.16.3 snapshot pr

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V1.16.4 snapshot pr

- RELEASE_NOTES.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/RestResponseController.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/Scheduler.java
> [GP-4411] Endpoint to remove the cache for a run by name

- README.md
- RELEASE_NOTES.md
- docs/illuminasetup.md
- docs/installation.md
- pom.xml
- scanner/pom.xml
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/RestResponseController.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/ScannerAppListener.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/SwaggerConfig.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/UserInterfaceController.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultPacBio.java
- scanner/src/main/webapp/WEB-INF/runscanner-servlet.xml
- scanner/src/main/webapp/WEB-INF/web.xml
JIRA Ticket: https://jira.oicr.on.ca/browse/GLT-4286
> [GLT-4286] updated to Spring 6

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V2.0.1 snapshot pr

- RELEASE_NOTES.md
- scanner/pom.xml
> fixed missing parameter name information

- RELEASE_NOTES.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/LatencyHistogram.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/Scheduler.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/StreamCountSpy.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
JIRA Ticket: n/a
This PR is only for the "fixed missing metrics" commit. The previous commit is covered by a separate PR, but included here to avoid merge conflict later.
> Fix prometheus

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V2.0.2 snapshot pr

- RELEASE_NOTES.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/DefaultIllumina.java
JIRA Ticket: N/A
I would return the switch if the code formatter would let me
> New RunErrored status found

- RELEASE_NOTES.md
- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V2.1.1 snapshot pr

- RELEASE_NOTES.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/UserInterfaceController.java
- scanner/src/main/webapp/WEB-INF/web.xml
JIRA Ticket: https://jira.oicr.on.ca/browse/GLT-4370
> [GLT-4370] added custom error page

- dto/pom.xml
- pom.xml
- scanner/pom.xml
> V2.1.2 snapshot pr

- RELEASE_NOTES.md
> fixed changelog

- RELEASE_NOTES.md
- docs/appendices.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/RevioPacBioProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/RunProcessor.java
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/processor/V2PacBioProcessor.java
- scanner/src/test/java/ca/on/oicr/gsi/runscanner/scanner/processor/V2PacBioProcessorTest.java
JIRA Ticket: https://jira.oicr.on.ca/browse/GLT-4395
> [GLT-4395] fixed scanning Vega runs

- RELEASE_NOTES.md
- scanner/src/main/java/ca/on/oicr/gsi/runscanner/scanner/SwaggerConfig.java
JIRA Ticket: https://jira.oicr.on.ca/browse/GLT-4396
> [GLT-4396] fixed bad URLs in Swagger docs
